[tool.poetry]
name = "devops-exercise"
version = "0.2.0"
description = ""
authors = ["voteshield"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
